/*
 * SPDX-FileCopyrightText: 2023 Tommaso Fontana
 * SPDX-FileCopyrightText: 2023 Inria
 * SPDX-FileCopyrightText: 2023 Sebastiano Vigna
 *
 * SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
 */

/*!

Traits for reading and writing instantaneous codes.

This modules contains code for reading and writing instantaneous codes.
Codewords are uniformely indexed from 0 for codes. For example, the
first few words of [unary](crate::traits::BitRead::read_unary),
[γ](gamma), and [δ](delta) codes are:

| Arg |  unary   |    γ    |     δ    |
|-----|---------:|--------:|---------:|
| 0   |        1 |       1 |        1 |
| 1   |       01 |     010 |     0100 |
| 2   |      001 |     011 |     0101 |
| 3   |     0001 |   00100 |    01100 |
| 4   |    00001 |   00101 |    01101 |
| 5   |   000001 |   00110 |    01110 |
| 6   |  0000001 |   00111 |    01111 |
| 7   | 00000001 | 0001000 | 00100000 |

Each
code is implemented as a pair of traits for reading and writing (e.g., [`GammaRead`]
and [`GammaWrite`]). The traits for reading depend on the trait [`BitRead`](crate::traits::BitRead), whereas
the traits for writing depend on the trait [`BitWrite`](crate::traits::BitWrite).

Some codes have associated decoding tables that are generated by a Python script. In this case,
there are parametric traits (e.g., [`GammaReadParam`] and [`GammaWriteParam`]) with methods
that let you specify whether to use a table or not.

All this logic is hidden by the traits [`table_params::ReadParams`] and [`table_params::WriteParams`],
which contains decision for the Boolean parameters.
[`BufBitReader`](crate::impls::BufBitReader) and [`BufBitWriter`](crate::impls::BufBitWriter) have a
parameter `DC` that is a type implementing [`table_params::ReadParams`] or [`table_params::WriteParams`],
and use by default the type [`table_params::DefaultReadParams`] or [`table_params::DefaultWriteParams`],
which contains reasonable default choices.

*/

/// Typed names for instantaneous codes.
///
/// Not all codes are currenly implemented.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "fuzz", derive(arbitrary::Arbitrary))]
pub enum Code {
    Unary,
    Gamma,
    Delta,
    Zeta { k: u64 },
    Golomb { b: u64 },
    SkewedGolomb { b: u64 },
    MinimalBinary { k: u64 },
    Nibble,
}

pub mod table_params;

pub mod gamma;

pub use gamma::{
    len_gamma, len_gamma_param, GammaRead, GammaReadParam, GammaWrite, GammaWriteParam,
};

pub mod delta;
pub use delta::{
    len_delta, len_delta_param, DeltaRead, DeltaReadParam, DeltaWrite, DeltaWriteParam,
};

pub mod minimal_binary;
pub use minimal_binary::{len_minimal_binary, MinimalBinaryRead, MinimalBinaryWrite};

pub mod zeta;
pub use zeta::{len_zeta, len_zeta_param, ZetaRead, ZetaReadParam, ZetaWrite, ZetaWriteParam};

pub mod delta_tables;
pub mod gamma_tables;
pub mod unary_tables;
pub mod zeta_tables;

mod stats;
pub use stats::*;
